### ISSUE TITLE
Schedule Name Selector

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/grafana-schedule-panel-build#3]
The Schedule Name selector currently allows the dashboard user to add Schedule Names.  This should not be possible.  

The Schedule Names should be configured only from the grafana panel `edit` menu.  Within the `edit` menu, there should be a field to add to a list of pre-defined Schedule Names.   The user should only be able to select from this list of pre-defined names. 

![image](https://user-images.githubusercontent.com/40550860/105917645-bf854b00-6086-11eb-9087-2308f1a3e469.png)

![image](https://user-images.githubusercontent.com/40550860/105918325-d9735d80-6087-11eb-9c20-a6023d998aa1.png)

**Comment by CanuckMarc** [comment]
Same as https://github.com/NubeIO/grafana-schedule-panel-build/issues/1

**Comment by sanjevShakya** [comment]
@CanuckMarc 
Can you confirm the following things:
1.  if this schedule name applies to the holiday event as well?
2. Can the title(schedule name in Weekly and Daily events) be overridden by the user or restricted to only the schedule names predefined in the side panel?

**Comment by CanuckMarc** [comment]
1. I don't think we have quite decided how the `holiday` schedule will be implemented (i don't think it does much right now).  For now, the pre-defined schedule options should apply to the `holiday` Schedule Name select too. 

2. No, the user should not be able to enter their own Schedule Names.  All options should be pre-defined in edit settings.

If you have more time after, check out the other schedule issues, there are a few others that might be easy fixes.

**Comment by sanjevShakya** [comment]
Yes, I have checked them out and figured out the problem is making them available for edit for the user.
Hey, Can you provide me feedback on this UI that I've made for the schedule names to be added from the config?
Haven't finished it yet but is this something that you want?
[DEMO](https://www.loom.com/share/89c19d99e99d4b518c2c0f23164149dd)

**Comment by CanuckMarc** [comment]
yes, that looks good for the settings interface.  Then user just needs to be able to select from that list from `event` `weekly` or `holiday` schedule making popup.
